#!/bin/sh
# THIS NEEDS UPGRADING SINCE MOVING FROM DOCPAD TO NPM

git up
# npm run build:dist
git add dist
git commit -m "Update static build - `date -u`"
git subtree push --prefix dist 5apps master
git push origin master
